import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,symlink,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';

test('local checker: real structure, dependency, compilation and security failures',async t=>{
  const root=await mkdtemp(path.join(tmpdir(),'imagine-check-test-'));
  const app=process.cwd();let service;
  t.after(async()=>{service?.kill();await rm(root,{recursive:true,force:true});});
  await mkdir(path.join(root,'.imagine'));
  await mkdir(path.join(root,'src/components/Card/assets'),{recursive:true});
  await symlink(path.join(app,'node_modules'),path.join(root,'node_modules'),'dir');
  const put=(p,v)=>writeFile(path.join(root,p),typeof v==='string'?v:JSON.stringify(v));
  await put('package.json',{dependencies:{react:'latest'}});
  await put('tsconfig.json',{compilerOptions:{target:'ES2022',module:'ESNext',moduleResolution:'Bundler',jsx:'react-jsx',skipLibCheck:true,strict:true,esModuleInterop:true}});
  await put('mock-github.mjs',`import {readFileSync,readdirSync} from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const root=process.env.IMAGINE_PROJECT_ROOT;const original=globalThis.fetch;
globalThis.fetch=async(url,options)=>{
 if(!String(url).startsWith('https://api.github.com/repos/fixture/repo/'))return original(url,options);
 const files=['.imagine/manifest.json','package.json','tsconfig.json'];
 const walk=p=>{for(const e of readdirSync(path.join(root,p),{withFileTypes:true})){const next=p+'/'+e.name;e.isDirectory()?walk(next):files.push(next);}};walk('src/components');
 const sha=p=>{const b=readFileSync(path.join(root,p));return createHash('sha1').update('blob '+b.length+'\\0').update(b).digest('hex')};
 if(String(url).includes('/commits/'))return Response.json({sha:'fixture-commit',commit:{tree:{sha:'fixture-tree'}}});
 if(String(url).includes('/git/blobs/')){const wanted=String(url).split('/').pop();const file=files.find(p=>sha(p)===wanted);return file?Response.json({encoding:'base64',content:readFileSync(path.join(root,file)).toString('base64')}):new Response('',{status:404});}
 const tree=files.map(p=>({path:p,type:'blob',sha:sha(p)}));
 return Response.json({truncated:false,tree});
};`);
  service=spawn(process.execPath,['--import',path.join(root,'mock-github.mjs'),'server/lab.mjs'],{cwd:app,env:{...process.env,PORT:'0',IMAGINE_PROJECT_ROOT:root,IMAGINE_STATE_DIR:path.join(root,'.imagine-local')},stdio:['ignore','pipe','pipe']});
  const base=await new Promise((resolve,reject)=>{let log='';const timer=setTimeout(()=>reject(new Error('server timeout')),10000);service.on('error',reject);service.stdout.on('data',b=>{log+=b;const m=log.match(/http:\/\/127.0.0.1:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});});
  const call=async(p='check',data={})=>(await fetch(base+'/api/lab/'+p,{method:'POST',headers:{'X-Imagine-Request':'local','Content-Type':'application/json'},body:JSON.stringify(data)})).json();
  const get=async p=>(await (await fetch(base+'/api/lab/'+p)).json());
  await t.test('missing manifest is not success',async()=>assert.match((await call()).error,/manifest/));
  const component={componentId:'card',name:'测试卡片',category:'展示',path:'src/components/Card',source:'fixture',status:'ready',framework:'react'};
  const manifest={schemaVersion:1,project:'test fixture',components:[component]};
  await put('.imagine/manifest.json',manifest);
  await t.test('missing README produces actionable issue',async()=>assert.ok((await call()).issues.some(s=>s.includes('README'))));
  await put('src/components/Card/README.md','# 用途\n测试\n# Props\n无\n# 依赖\nReact\n# 限制\n仅测试\n# 示例\n见 example.tsx');
  await put('src/components/Card/index.tsx','export default function Card(){return <button>测试</button>}');
  await put('src/components/Card/example.tsx',"import Card from './index'; export default function Example(){return <Card/>}");
  await put('src/components/Card/assets/.gitkeep','');
  await t.test('connect indexes a remote manifest without a local checkpoint',async()=>{const result=await call('connect',{repo:'fixture/repo',ref:'main'});assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.components[0].componentId,'card');assert.match(result.components[0].url,/fixture-commit/);});
  await t.test('valid actual TSX example builds',async()=>{const result=await call();assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.checks.length,3);});
  await t.test('matching remote fixture produces pinned catalog',async()=>{const result=await call('sync',{repo:'fixture/repo',ref:'main'});assert.equal(result.ok,true,JSON.stringify(result));assert.match(result.components[0].url,/fixture-commit/);});
  await t.test('successful sync persists repository connection and catalog',async()=>{const connection=await get('connection');assert.equal(connection.ok,true);assert.equal(connection.connection.repo,'fixture/repo');assert.equal(connection.connection.ref,'main');const saved=JSON.parse(await readFile(path.join(root,'.imagine-local/github-state.json'),'utf8'));assert.equal(saved.catalog.commit,'fixture-commit');assert.equal(saved.connection.status,'connected');});
  await put('src/components/Card/index.tsx','export default function Card(){const value: number="wrong";return <button>{value}</button>}');
  await t.test('changed files invalidate successful checkpoint',async()=>assert.match((await call('sync',{repo:'fixture/repo',ref:'main'})).error,/本地交付已变化/));
  await t.test('type error cannot pass',async()=>assert.equal((await call()).ok,false));
  await put('src/components/Card/index.tsx','export default function Card(){return <img src="./missing.png"/>}');
  await t.test('missing literal resource cannot pass',async()=>assert.match((await call()).issues.join(' '),/资源不存在/));
  await put('src/components/Card/index.tsx',"import {Plus} from 'lucide-react';export default function Card(){return <Plus/>}");
  await t.test('installed but undeclared dependency cannot pass',async()=>assert.match((await call()).issues.join(' '),/未在 package/));
  await put('.imagine/manifest.json',{...manifest,components:[{...component,path:'../../etc'}]});
  await t.test('path traversal rejected',async()=>assert.equal((await call()).ok,false));
  await t.test('cross origin requests rejected',async()=>{const r=await fetch(base+'/api/lab/check',{method:'POST',headers:{'X-Imagine-Request':'local',Origin:'https://evil.example'}});assert.equal(r.status,403);});
  await t.test('sync requires successful checkpoint',async()=>assert.match((await call('sync',{repo:'owner/repo',ref:'main'})).error,/先完成本地检查/));
});
