import http from 'node:http';
import {handleAgent} from './agent.mjs';
import {createReadStream, statSync} from 'node:fs';
import {extname, join, normalize} from 'node:path';

const port=Number(process.env.PORT||4174);
const distRoot=join(process.cwd(),'dist');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.webp':'image/webp','.avif':'image/avif','.woff2':'font/woff2'};

function sendJson(res,status,payload){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(payload))}
function readJson(req){return new Promise((resolve,reject)=>{let body='';req.on('data',chunk=>{body+=chunk;if(body.length>1024*1024){reject(new Error('请求内容过大'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch{reject(new Error('请求格式无效'))}});req.on('error',reject)})}
function parseFigmaLink(value){const url=new URL(value);if(!/(^|\.)figma\.com$/i.test(url.hostname))throw new Error('请输入有效的 Figma 链接');const match=url.pathname.match(/^\/(?:design|file)\/([^/]+)/);if(!match)throw new Error('链接中缺少 Figma 文件标识');const rawNode=url.searchParams.get('node-id');if(!rawNode)throw new Error('请使用包含 node-id 的单个画板链接');return{fileKey:match[1],nodeId:rawNode.replace(/-/g,':')}}
async function figmaRequest(path,token,stage='Figma'){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(`https://api.figma.com/v1${path}`,{headers:{'X-Figma-Token':token,'Accept':'application/json'},signal:controller.signal});const payload=await response.json().catch(()=>({}));if(!response.ok){const detail=String(payload.err||payload.message||'').trim();const message=response.status===401||response.status===403?`${stage}读取被拒绝${detail?`：${detail}`:'。请确认 Token 权限与文件访问权限。'}`:response.status===404?`${stage}不存在或当前账号无法访问。`:response.status===429?'Figma API 请求过于频繁，请稍后重试。':detail||`${stage}请求失败（${response.status}）`;const error=new Error(message);error.status=response.status;throw error}return payload}finally{clearTimeout(timer)}}
function scanNode(root){const counts={frames:0,components:0,instances:0,variables:0,textLayers:0};const variables=new Set();const collectVariables=value=>{if(!value)return;if(typeof value==='string'){variables.add(value);return}if(Array.isArray(value)){value.forEach(collectVariables);return}if(typeof value==='object')Object.values(value).forEach(collectVariables)};const visit=node=>{if(!node||typeof node!=='object')return;if(node.type==='FRAME'||node.type==='SECTION')counts.frames++;if(node.type==='COMPONENT'||node.type==='COMPONENT_SET')counts.components++;if(node.type==='INSTANCE')counts.instances++;if(node.type==='TEXT')counts.textLayers++;collectVariables(node.boundVariables);if(Array.isArray(node.children))node.children.forEach(visit)};visit(root);counts.variables=variables.size;return counts}
function cssColor(color,opacity=1){if(!color)return undefined;const alpha=(color.a??1)*opacity;return `rgba(${Math.round((color.r??0)*255)},${Math.round((color.g??0)*255)},${Math.round((color.b??0)*255)},${Math.max(0,Math.min(1,alpha))})`}
function firstPaint(paints,type){return Array.isArray(paints)?paints.find(paint=>paint?.visible!==false&&paint?.type===type):undefined}
function collectImageRefs(root){const refs=new Set();const visit=node=>{const image=firstPaint(node?.fills,'IMAGE');if(image?.imageRef)refs.add(image.imageRef);if(Array.isArray(node?.children))node.children.forEach(visit)};visit(root);return refs}
function nodeShadow(effects){const effect=Array.isArray(effects)?effects.find(item=>item?.visible!==false&&item?.type==='DROP_SHADOW'):null;if(!effect)return undefined;return `${effect.offset?.x||0}px ${effect.offset?.y||0}px ${effect.radius||0}px ${effect.spread||0}px ${cssColor(effect.color)}`}
function toRenderNode(node,parentBox,imageMap,depth=0){if(!node||node.visible===false||depth>40)return null;const box=node.absoluteBoundingBox||node.absoluteRenderBounds;if(!box||!Number.isFinite(box.width)||!Number.isFinite(box.height))return null;const solid=firstPaint(node.fills,'SOLID');const image=firstPaint(node.fills,'IMAGE');const stroke=firstPaint(node.strokes,'SOLID');const text=node.type==='TEXT';const font=node.style||{};const style={left:box.x-parentBox.x,top:box.y-parentBox.y,width:box.width,height:box.height,opacity:node.opacity??1,overflow:node.clipsContent?'hidden':'visible',backgroundColor:cssColor(solid?.color,solid?.opacity??1),backgroundImage:image?.imageRef&&imageMap[image.imageRef]?`url(${imageMap[image.imageRef]})`:undefined,backgroundSize:image?.scaleMode==='FIT'?'contain':'cover',backgroundPosition:'center',backgroundRepeat:'no-repeat',border:stroke?`${Math.max(1,node.strokeWeight||1)}px solid ${cssColor(stroke.color,stroke.opacity??1)}`:undefined,borderRadius:Array.isArray(node.rectangleCornerRadii)?node.rectangleCornerRadii.map(value=>`${value}px`).join(' '):node.cornerRadius!=null?`${node.cornerRadius}px`:undefined,boxShadow:nodeShadow(node.effects),transform:node.rotation?`rotate(${-node.rotation}deg)`:undefined,color:text?cssColor(solid?.color,solid?.opacity??1):undefined,fontFamily:text?font.fontFamily:undefined,fontSize:text?font.fontSize:undefined,fontWeight:text?font.fontWeight:undefined,lineHeight:text?(font.lineHeightPx?`${font.lineHeightPx}px`:undefined):undefined,letterSpacing:text?(font.letterSpacing?`${font.letterSpacing}px`:undefined):undefined,textAlign:text?String(font.textAlignHorizontal||'LEFT').toLowerCase():undefined,whiteSpace:text?'pre-wrap':undefined};const children=Array.isArray(node.children)?node.children.map(child=>toRenderNode(child,box,imageMap,depth+1)).filter(Boolean):[];return{id:node.id,name:node.name||node.type,type:node.type,text:text?node.characters||'':undefined,style,children}}
async function inspectFigma(req,res){try{const {url,token}=await readJson(req);if(typeof token!=='string'||token.trim().length<8)throw new Error('Access Token 无效或不完整');const {fileKey,nodeId}=parseFigmaLink(String(url||''));const cleanToken=token.trim();await figmaRequest('/me',cleanToken,'Token 身份');const file=await figmaRequest(`/files/${encodeURIComponent(fileKey)}?depth=1`,cleanToken,'Figma 文件');const nodes=await figmaRequest(`/files/${encodeURIComponent(fileKey)}/nodes?ids=${encodeURIComponent(nodeId)}&geometry=paths`,cleanToken,'目标画板');const entry=nodes.nodes?.[nodeId]||nodes.nodes?.[nodeId.replace(/:/g,'-')];if(!entry?.document)throw new Error('Figma 返回结果中没有找到目标画板');const target=entry.document;const counts=scanNode(target);const pages=Array.isArray(file.document?.children)?file.document.children.filter(item=>item.type==='CANVAS').length:0;let imageUrl;try{const image=await figmaRequest(`/images/${encodeURIComponent(fileKey)}?ids=${encodeURIComponent(nodeId)}&format=png&scale=1`,cleanToken,'画板预览');imageUrl=image.images?.[nodeId]||image.images?.[nodeId.replace(/:/g,'-')]||undefined}catch{imageUrl=undefined}let imageMap={};if(collectImageRefs(target).size){try{const images=await figmaRequest(`/files/${encodeURIComponent(fileKey)}/images`,cleanToken,'图片资源');imageMap=images.meta?.images||{}}catch{imageMap={}}}const rootBox=target.absoluteBoundingBox||target.absoluteRenderBounds;const renderTree=rootBox?toRenderNode(target,{x:rootBox.x,y:rootBox.y},imageMap):undefined;sendJson(res,200,{source:'figma',fileKey,nodeId,fileName:file.name||'Figma 项目',nodeName:target.name||'未命名画板',projectName:target.name||file.name||'Figma 项目',imageUrl,lastModified:file.lastModified,version:file.version,renderTree,counts:{pages,frames:counts.frames,components:counts.components,instances:counts.instances,variables:counts.variables,textLayers:counts.textLayers}})}catch(error){const status=Number(error?.status)||400;sendJson(res,status>=400&&status<600?status:500,{error:error?.name==='AbortError'?'连接 Figma 超时，请检查网络后重试。':error instanceof Error?error.message:'无法读取 Figma 画板'})}}
function serveStatic(req,res){let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{res.writeHead(400);res.end('Bad Request');return}const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/, '');const safe=normalize(relative).replace(/^(\.\.(\/|\\|$))+/, '');let filePath=join(distRoot,safe);try{if(!statSync(filePath).isFile())filePath=join(distRoot,'index.html')}catch{filePath=join(distRoot,'index.html')}const type=mime[extname(filePath).toLowerCase()]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':filePath.endsWith('index.html')?'no-cache':'public, max-age=3600'});if(req.method==='HEAD'){res.end();return}createReadStream(filePath).on('error',()=>{if(!res.headersSent){res.writeHead(503,{'Content-Type':'text/plain; charset=utf-8','Retry-After':'2'});res.end('页面正在构建，请稍后刷新')}else res.destroy()}).pipe(res)}

const server=http.createServer(async(req,res)=>{if(await handleAgent(req,res))return;if(req.method==='GET'&&req.url==='/api/health'){sendJson(res,200,{ok:true});return}if(req.method==='POST'&&req.url==='/api/figma/inspect'){inspectFigma(req,res);return}if(req.url?.startsWith('/api/')){sendJson(res,404,{error:'接口不存在'});return}serveStatic(req,res)});
server.listen(port,'127.0.0.1',()=>console.log(`Imagine Lab preview ready at http://127.0.0.1:${port}`));
